export const IELTS_VOCABULARY = {
  academic: [
    "analyze",
    "assess",
    "comprehensive",
    "demonstrate",
    "evaluate",
    "hypothesis",
    "methodology",
    "paradigm",
    "theoretical",
    "empirical",
    "coherent",
    "criterion",
    "deduce",
    "implicit",
    "inference",
    "paradigm",
    "preliminary",
    "subsequent",
    "synthesis",
    "validate",
  ],
  environment: [
    "biodiversity",
    "conservation",
    "deforestation",
    "ecosystem",
    "emission",
    "renewable",
    "sustainable",
    "pollution",
    "habitat",
    "endangered",
    "climate",
    "fossil",
    "greenhouse",
    "recycle",
    "contamination",
    "preservation",
    "ecological",
    "carbon",
    "depletion",
    "erosion",
  ],
  technology: [
    "innovation",
    "automation",
    "artificial",
    "digital",
    "algorithm",
    "breakthrough",
    "sophisticated",
    "obsolete",
    "cutting-edge",
    "revolutionary",
    "interface",
    "bandwidth",
    "cybersecurity",
    "encryption",
    "virtual",
    "augmented",
    "blockchain",
    "quantum",
    "nanotechnology",
    "biotechnology",
  ],
  society: [
    "diversity",
    "inequality",
    "discrimination",
    "integration",
    "segregation",
    "prosperity",
    "poverty",
    "welfare",
    "infrastructure",
    "urbanization",
    "migration",
    "demographic",
    "multicultural",
    "cohesion",
    "disparity",
    "marginalized",
    "empowerment",
    "solidarity",
    "tolerance",
    "prejudice",
  ],
  economy: [
    "inflation",
    "recession",
    "prosperity",
    "commodity",
    "investment",
    "entrepreneur",
    "revenue",
    "expenditure",
    "deficit",
    "surplus",
    "fluctuation",
    "subsidy",
    "tariff",
    "monopoly",
    "competition",
    "privatization",
    "globalization",
    "capitalism",
    "recession",
    "bankruptcy",
  ],
  education: [
    "curriculum",
    "pedagogy",
    "literacy",
    "proficiency",
    "competence",
    "vocational",
    "tertiary",
    "tuition",
    "scholarship",
    "apprenticeship",
    "assessment",
    "accreditation",
    "enrollment",
    "dropout",
    "graduate",
    "undergraduate",
    "dissertation",
    "seminar",
    "tutorial",
    "lecture",
  ],
  health: [
    "epidemic",
    "pandemic",
    "immunity",
    "vaccination",
    "diagnosis",
    "treatment",
    "prevention",
    "chronic",
    "acute",
    "symptom",
    "therapy",
    "rehabilitation",
    "nutrition",
    "obesity",
    "sedentary",
    "wellness",
    "mental",
    "pharmaceutical",
    "clinical",
    "pathology",
  ],
  general: [
    "ubiquitous",
    "ephemeral",
    "resilient",
    "pragmatic",
    "ambiguous",
    "eloquent",
    "benevolent",
    "serendipity",
    "meticulous",
    "diligent",
    "inevitable",
    "substantial",
    "adequate",
    "crucial",
    "significant",
    "prominent",
    "fundamental",
    "essential",
    "vital",
    "paramount",
  ],
}

// Flatten all words into a single array for the flashcard system
export const WORDS: string[] = Object.values(IELTS_VOCABULARY).flat()

export const CATEGORY_NAMES: Record<string, string> = {
  academic: "آکادمیک و تحصیلی",
  environment: "محیط زیست",
  technology: "فناوری و تکنولوژی",
  society: "جامعه و اجتماع",
  economy: "اقتصاد و تجارت",
  education: "آموزش و پرورش",
  health: "سلامت و بهداشت",
  general: "عمومی و کاربردی",
}

// Get category for a specific word
export const getWordCategory = (word: string): string => {
  for (const [category, words] of Object.entries(IELTS_VOCABULARY)) {
    if (words.includes(word)) {
      return category
    }
  }
  return "general"
}
